# Generated by Django 5.2.6 on 2026-04-30 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('cleaning', 'Cleaning'), ('appliance_repair', 'Appliance Repair'), ('carpenter', 'Carpenter'), ('other', 'Other')], max_length=40)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('is_active_partner', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
