# Generated by Django 5.2.6 on 2026-05-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.CharField(max_length=255)),
                ('issue_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='appusers.partnerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
