# Generated by Django 5.2.6 on 2026-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0002_partnerbookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerbookingrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerbookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
