# Generated by Codex on 2026-05-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appusers", "0003_partnerbookingrequest_preferred_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("price", models.PositiveIntegerField()),
                ("rating", models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ("description", models.TextField()),
                ("image", models.URLField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("details", models.TextField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=80)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("available_pincodes", models.JSONField(blank=True, default=list)),
                ("questions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="CustomerBooking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_name", models.CharField(max_length=120)),
                ("service_slug", models.SlugField(blank=True)),
                ("service_image", models.URLField(blank=True)),
                ("service_category", models.CharField(blank=True, max_length=80)),
                ("configured_price", models.PositiveIntegerField()),
                ("config_options", models.JSONField(blank=True, default=dict)),
                ("customer_name", models.CharField(max_length=120)),
                ("customer_phone", models.CharField(max_length=20)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("pincode", models.CharField(db_index=True, max_length=10)),
                ("payment_method", models.CharField(choices=[("online", "Online"), ("cod", "Cash on Delivery")], default="cod", max_length=20)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="confirmed", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="bookings", to="appusers.servicecatalog")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="customer_bookings", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PartnerServiceOffering",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("image", models.URLField()),
                ("price", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("partner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="service_offerings", to="appusers.partnerprofile")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
