# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appusers", "0005_seed_service_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbooking",
            name="checkout_group",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customerbooking",
            name="gateway_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name="customerbooking",
            name="gateway_payment_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="customerbooking",
            name="gateway_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerbooking",
            name="payment_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("authorized", "Authorized"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
