# Generated by Django 5.2.6 on 2026-05-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0007_partnerbookingrequest_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerbookingrequest',
            name='service_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerbookingrequest',
            name='service_price',
            field=models.PositiveIntegerField(default=299),
        ),
        migrations.AlterField(
            model_name='partnerbookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('paid', 'Paid / Confirmed')], default='pending', max_length=20),
        ),
    ]
