# Generated by Django 5.2.6 on 2026-05-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0008_partnerbookingrequest_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbooking',
            name='service_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='partnerserviceoffering',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='servicecatalog',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
