# Generated by Django 5.2.6 on 2026-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0009_alter_customerbooking_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerserviceoffering',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
