# Generated by Django 5.2.6 on 2026-05-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0010_alter_partnerserviceoffering_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbooking',
            name='partner_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bookings', to='appusers.partnerbookingrequest'),
        ),
        migrations.AlterField(
            model_name='partnerbookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('paid', 'Paid / Confirmed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
