# Generated by Django 5.2.6 on 2026-05-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0011_customerbooking_partner_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerbookingrequest',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
